AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Scraping test for Villa based in Scrapy

Globals:
  Function:
    Timeout: 15

Resources:
  VillaTesterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: villa_tester/
      Handler: handler.lambda_handler
      Runtime: python3.8

Outputs:
  VillaTesterFunction:
    Description: "VillaTester Lambda Function ARN"
    Value: !GetAtt VillaTesterFunction.Arn
  VillaTesterFunctionIamRole:
    Description: "Implicit IAM Role created for VillaTester function"
    Value: !GetAtt VillaTesterFunctionRole.Arn
